import { setPrototypeOf } from "./shared/object.js";
import "./interface/event-target.js";
import "./interface/node-list.js";
import "./interface/event.js";
import { illegalConstructor } from "./shared/facades.js";
import "./html/element.js";
import "./html/template-element.js";
import "./html/html-element.js";
import "./html/script-element.js";
import "./html/frame-element.js";
import "./html/i-frame-element.js";
import "./html/object-element.js";
import "./html/head-element.js";
import "./html/body-element.js";
import "./html/style-element.js";
import "./html/time-element.js";
import "./html/field-set-element.js";
import "./html/embed-element.js";
import "./html/hr-element.js";
import "./html/progress-element.js";
import "./html/paragraph-element.js";
import "./html/table-element.js";
import "./html/frame-set-element.js";
import "./html/li-element.js";
import "./html/base-element.js";
import "./html/data-list-element.js";
import "./html/input-element.js";
import "./html/param-element.js";
import "./html/media-element.js";
import "./html/audio-element.js";
import "./html/heading-element.js";
import "./html/directory-element.js";
import "./html/quote-element.js";
import "./html/canvas-element.js";
import "./html/legend-element.js";
import "./html/option-element.js";
import "./html/span-element.js";
import "./html/meter-element.js";
import "./html/video-element.js";
import "./html/table-cell-element.js";
import "./html/title-element.js";
import "./html/output-element.js";
import "./html/table-row-element.js";
import "./html/data-element.js";
import "./html/menu-element.js";
import "./html/select-element.js";
import "./html/br-element.js";
import "./html/button-element.js";
import "./html/map-element.js";
import "./html/opt-group-element.js";
import "./html/d-list-element.js";
import "./html/text-area-element.js";
import "./html/font-element.js";
import "./html/div-element.js";
import "./html/link-element.js";
import "./html/slot-element.js";
import "./html/form-element.js";
import "./html/image-element.js";
import "./html/pre-element.js";
import "./html/u-list-element.js";
import "./html/meta-element.js";
import "./html/picture-element.js";
import "./html/area-element.js";
import "./html/o-list-element.js";
import "./html/table-caption-element.js";
import "./html/anchor-element.js";
import "./html/label-element.js";
import "./html/unknown-element.js";
import "./html/mod-element.js";
import "./html/details-element.js";
import "./html/source-element.js";
import "./html/track-element.js";
import "./html/marquee-element.js";
import "./shared/html-classes.js";
import "./interface/custom-event.js";
import "./interface/input-event.js";
import { Document as Document$1 } from "./interface/document.js";
import "./dom/parser.js";
import "./shared/parse-json.js";
//#region node_modules/linkedom/esm/index.js
function Document() {
	illegalConstructor();
}
setPrototypeOf(Document, Document$1).prototype = Document$1.prototype;
//#endregion
export { Document };
